### ISSUE TITLE
All GMM models

### ISSUE THREAD

**Issue by haohaiziround** [Tobias-Kohn/PyFOPPL-2#2]
Here we list a collection of all gmm models, from easy to hard. Might write `loop` differently. Will update after talking to Tobias.

**gmm_a**
RVs: `zs`, `mus`
```clojure
(defn sample-components [_ zs pi]
  (let [z (sample (categorical pi))]
    (conj zs z)))

(defn observe-data [n _ ys zs mus]
  (let [y (get ys n)
        z (get zs n)
        mu (get mus z)]
    (observe (normal mu 1) y)
    nil))

(let [ys      (vector -2.0  -2.5  -1.7  -1.9  -2.2
                      1.5  2.2  3  1.2  2.8)
      pi [0.5 0.5]
      zs  (loop 10 (vector) sample-components pi)
      mus (vector (sample (normal 0 100))   ; std = 10
                  (sample (normal 0 100)))]
  (loop 10 nil observe-data ys zs mus)
  (vector mus zs))
```

**gmm_b**
RVs: `pi`, `zs`, `mus`
```clojure
(defn sample-components [_ zs pi]
  (let [z (sample (categorical pi))]
    (conj zs z)))

(defn observe-data [n _ ys zs mus]
  (let [y (get ys n)
        z (get zs n)
        mu (get mus z)]
    (observe (normal mu 1) y)
    nil))

(let [ys      (vector -2.0  -2.5  -1.7  -1.9  -2.2
                      1.5  2.2  3  1.2  2.8)
      k 2
      pi (sample (dirichlet [1.0 1.0]))
      zs  (loop 10 (vector) sample-components pi)
      mus (vector (sample (normal 0 100))   ; std = 10
                  (sample (normal 0 100)))]
  (loop 10 nil observe-data ys zs mus)
  (vector pi zs mus))
```

**gmm_c**
RVs: `pi`, `zs`, `mus`, `taus`
```clojure
;; fix pi, unknown prior mean for the center of each cluster

(defn sample-components [_ zs pi]
  (let [z (sample (categorical pi))]
    (conj zs z)))

(defn observe-data [n _ ys zs mus taus]
  (let [y (get ys n)
        z (get zs n)
        mu (get mus z)
        tau (get taus z)]
    (observe (normal mu (/ 1 tau)) y)
    nil))

(let [ys      (vector -2.0  -2.5  -1.7  -1.9  -2.2
                      1.5  2.2  3  1.2  2.8)
      k 2
      pi (sample (dirichlet [1.0 1.0]))
      zs  (loop 10 (vector) sample-components pi)
      mus (vector (sample (normal 0 100))   ; std = 10
                  (sample (normal 0 100)))
      taus (vector (sample (gamma 1 1))
                  (sample (gamma 1 1)))]
  (loop 10 nil observe-data ys zs mus taus)
  (vector pi zs mus taus ))
```

**Comment by haohaiziround** [comment]
The first thing is the `loop`.

We get 100 `zs`, which might because inside each step of the observe loop we generate 10 `zs`.

**Comment by bayesianbrad** [comment]
For gmm_B and gmm_C we get the following errors:
```python

//Users/bradley/miniconda3/envs/pyfo/bin/python3.6 /Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/unittests/models/gmm/run_gmm_1d.py
==================================================
Now generating prior python code 
# data_30001
state['data_30001'] = [-2.0, -2.5, -1.7, -1.9, -2.2, 1.5, 2.2, 3, 1.2, 2.8]
# x30002
state['x30002'] = dist.Dirichlet([1.0, 1.0]).sample()
# x30003
state['x30003'] = dist.Categorical(state['x30002']).sample()
# x30004
state['x30004'] = dist.Categorical(state['x30002']).sample()
# x30005
state['x30005'] = dist.Categorical(state['x30002']).sample()
# x30006
state['x30006'] = dist.Categorical(state['x30002']).sample()
# x30007
state['x30007'] = dist.Categorical(state['x30002']).sample()
# x30008
state['x30008'] = dist.Categorical(state['x30002']).sample()
# x30009
state['x30009'] = dist.Categorical(state['x30002']).sample()
# x30010
state['x30010'] = dist.Categorical(state['x30002']).sample()
# x30011
state['x30011'] = dist.Categorical(state['x30002']).sample()
# x30012
state['x30012'] = dist.Categorical(state['x30002']).sample()
# x30013
state['x30013'] = dist.Normal(0, 100).sample()
# x30014
state['x30014'] = dist.Normal(0, 100).sample()
# y30015
state['y30015'] = -2.0
# y30016
state['y30016'] = -2.5
# y30017
state['y30017'] = -1.7
# y30018
state['y30018'] = -1.9
# y30019
state['y30019'] = -2.2
# y30020
state['y30020'] = 1.5
# y30021
state['y30021'] = 2.2
# y30022
state['y30022'] = 3
# y30023
state['y30023'] = 1.2
# y30024
state['y30024'] = 2.8
==================================================
Now generating posterior python code 
# data_30001
state['data_30001'] = [-2.0, -2.5, -1.7, -1.9, -2.2, 1.5, 2.2, 3, 1.2, 2.8]
# x30002
log_pdf += dist.Dirichlet([1.0, 1.0]).log_pdf(state['x30002'])
# x30003
log_pdf += dist.Categorical(state['x30002']).log_pdf(state['x30003'])
# x30004
log_pdf += dist.Categorical(state['x30002']).log_pdf(state['x30004'])
# x30005
log_pdf += dist.Categorical(state['x30002']).log_pdf(state['x30005'])
# x30006
log_pdf += dist.Categorical(state['x30002']).log_pdf(state['x30006'])
# x30007
log_pdf += dist.Categorical(state['x30002']).log_pdf(state['x30007'])
# x30008
log_pdf += dist.Categorical(state['x30002']).log_pdf(state['x30008'])
# x30009
log_pdf += dist.Categorical(state['x30002']).log_pdf(state['x30009'])
# x30010
log_pdf += dist.Categorical(state['x30002']).log_pdf(state['x30010'])
# x30011
log_pdf += dist.Categorical(state['x30002']).log_pdf(state['x30011'])
# x30012
log_pdf += dist.Categorical(state['x30002']).log_pdf(state['x30012'])
# x30013
log_pdf += dist.Normal(0, 100).log_pdf(state['x30013'])
# x30014
log_pdf += dist.Normal(0, 100).log_pdf(state['x30014'])
# y30015
log_pdf += dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30003'])], 1).log_pdf(-2.0)
# y30016
log_pdf += dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30004'])], 1).log_pdf(-2.5)
# y30017
log_pdf += dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30005'])], 1).log_pdf(-1.7)
# y30018
log_pdf += dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30006'])], 1).log_pdf(-1.9)
# y30019
log_pdf += dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30007'])], 1).log_pdf(-2.2)
# y30020
log_pdf += dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30008'])], 1).log_pdf(1.5)
# y30021
log_pdf += dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30009'])], 1).log_pdf(2.2)
# y30022
log_pdf += dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30010'])], 1).log_pdf(3)
# y30023
log_pdf += dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30011'])], 1).log_pdf(1.2)
# y30024
log_pdf += dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30012'])], 1).log_pdf(2.8)
==================================================
==================================================
Now generating posterior python code 
Vertices V:
  x30002:
	Ancestors: 
	Distribution: dist.Dirichlet([1.0, 1.0])
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: pi
	Code: lambda state: dist.Dirichlet([1.0, 1.0])
	Sample-Size: 1
	Support-size: 2
	Line: 70
  x30003:
	Ancestors: x30002
	Distribution: dist.Categorical(x30002)
	Dependent Conditions: 
	Distr-Type: discrete
	Original-Name: z
	Code: lambda state: dist.Categorical(state['x30002'])
	Sample-Size: 1
	Line: 57
  x30004:
	Ancestors: x30002
	Distribution: dist.Categorical(x30002)
	Dependent Conditions: 
	Distr-Type: discrete
	Original-Name: z
	Code: lambda state: dist.Categorical(state['x30002'])
	Sample-Size: 1
	Line: 57
  x30005:
	Ancestors: x30002
	Distribution: dist.Categorical(x30002)
	Dependent Conditions: 
	Distr-Type: discrete
	Original-Name: z
	Code: lambda state: dist.Categorical(state['x30002'])
	Sample-Size: 1
	Line: 57
  x30006:
	Ancestors: x30002
	Distribution: dist.Categorical(x30002)
	Dependent Conditions: 
	Distr-Type: discrete
	Original-Name: z
	Code: lambda state: dist.Categorical(state['x30002'])
	Sample-Size: 1
	Line: 57
  x30007:
	Ancestors: x30002
	Distribution: dist.Categorical(x30002)
	Dependent Conditions: 
	Distr-Type: discrete
	Original-Name: z
	Code: lambda state: dist.Categorical(state['x30002'])
	Sample-Size: 1
	Line: 57
  x30008:
	Ancestors: x30002
	Distribution: dist.Categorical(x30002)
	Dependent Conditions: 
	Distr-Type: discrete
	Original-Name: z
	Code: lambda state: dist.Categorical(state['x30002'])
	Sample-Size: 1
	Line: 57
  x30009:
	Ancestors: x30002
	Distribution: dist.Categorical(x30002)
	Dependent Conditions: 
	Distr-Type: discrete
	Original-Name: z
	Code: lambda state: dist.Categorical(state['x30002'])
	Sample-Size: 1
	Line: 57
  x30010:
	Ancestors: x30002
	Distribution: dist.Categorical(x30002)
	Dependent Conditions: 
	Distr-Type: discrete
	Original-Name: z
	Code: lambda state: dist.Categorical(state['x30002'])
	Sample-Size: 1
	Line: 57
  x30011:
	Ancestors: x30002
	Distribution: dist.Categorical(x30002)
	Dependent Conditions: 
	Distr-Type: discrete
	Original-Name: z
	Code: lambda state: dist.Categorical(state['x30002'])
	Sample-Size: 1
	Line: 57
  x30012:
	Ancestors: x30002
	Distribution: dist.Categorical(x30002)
	Dependent Conditions: 
	Distr-Type: discrete
	Original-Name: z
	Code: lambda state: dist.Categorical(state['x30002'])
	Sample-Size: 1
	Line: 57
  x30013:
	Ancestors: 
	Distribution: dist.Normal(0, 100)
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal(0, 100)
	Sample-Size: 1
	Line: 72
  x30014:
	Ancestors: 
	Distribution: dist.Normal(0, 100)
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal(0, 100)
	Sample-Size: 1
	Line: 73
  y30015:
	Ancestors: x30002, x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012, x30013, x30014
	Distribution: dist.Normal([x30013, x30014][x30003], 1)
	Observation: -2.0
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30003'])], 1)
	Sample-Size: 1
	Line: 64
  y30016:
	Ancestors: x30002, x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012, x30013, x30014
	Distribution: dist.Normal([x30013, x30014][x30004], 1)
	Observation: -2.5
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30004'])], 1)
	Sample-Size: 1
	Line: 64
  y30017:
	Ancestors: x30002, x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012, x30013, x30014
	Distribution: dist.Normal([x30013, x30014][x30005], 1)
	Observation: -1.7
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30005'])], 1)
	Sample-Size: 1
	Line: 64
  y30018:
	Ancestors: x30002, x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012, x30013, x30014
	Distribution: dist.Normal([x30013, x30014][x30006], 1)
	Observation: -1.9
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30006'])], 1)
	Sample-Size: 1
	Line: 64
  y30019:
	Ancestors: x30002, x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012, x30013, x30014
	Distribution: dist.Normal([x30013, x30014][x30007], 1)
	Observation: -2.2
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30007'])], 1)
	Sample-Size: 1
	Line: 64
  y30020:
	Ancestors: x30002, x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012, x30013, x30014
	Distribution: dist.Normal([x30013, x30014][x30008], 1)
	Observation: 1.5
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30008'])], 1)
	Sample-Size: 1
	Line: 64
  y30021:
	Ancestors: x30002, x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012, x30013, x30014
	Distribution: dist.Normal([x30013, x30014][x30009], 1)
	Observation: 2.2
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30009'])], 1)
	Sample-Size: 1
	Line: 64
  y30022:
	Ancestors: x30002, x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012, x30013, x30014
	Distribution: dist.Normal([x30013, x30014][x30010], 1)
	Observation: 3
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30010'])], 1)
	Sample-Size: 1
	Line: 64
  y30023:
	Ancestors: x30002, x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012, x30013, x30014
	Distribution: dist.Normal([x30013, x30014][x30011], 1)
	Observation: 1.2
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30011'])], 1)
	Sample-Size: 1
	Line: 64
  y30024:
	Ancestors: x30002, x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012, x30013, x30014
	Distribution: dist.Normal([x30013, x30014][x30012], 1)
	Observation: 2.8
	Dependent Conditions: 
	Distr-Type: continuous
	Original-Name: -
	Code: lambda state: dist.Normal([state['x30013'], state['x30014']][runtime.index(state['x30012'])], 1)
	Sample-Size: 1
	Line: 64

Arcs A:
  (x30013, y30015), (x30007, y30016), (x30007, y30023), (x30002, x30005), (x30012, y30018), (x30002, x30010), (x30005, y30019), (x30002, y30024), (x30011, y30015), (x30006, y30021), (x30011, y30018), (x30009, y30021), (x30004, y30020), (x30003, y30016), (x30003, y30023), (x30003, y30022), (x30014, y30022), (x30006, y30024), (x30010, y30020), (x30012, y30015), (x30014, y30021), (x30003, y30021), (x30009, y30022), (x30007, y30021), (x30002, x30007), (x30002, x30006), (x30005, y30018), (x30005, y30020), (x30004, y30015), (x30004, y30016), (x30004, y30023), (x30002, y30021), (x30008, y30015), (x30012, y30016), (x30012, y30023), (x30013, y30019), (x30002, y30022), (x30003, y30017), (x30013, y30021), (x30010, y30018), (x30002, x30008), (x30002, y30019), (x30005, y30022), (x30002, y30018), (x30011, y30021), (x30006, y30017), (x30006, y30015), (x30005, y30021), (x30009, y30015), (x30011, y30022), (x30007, y30019), (x30012, y30017), (x30007, y30024), (x30002, x30004), (x30009, y30016), (x30009, y30023), (x30011, y30019), (x30014, y30024), (x30006, y30020), (x30010, y30021), (x30004, y30022), (x30012, y30021), (x30012, y30019), (x30014, y30015), (x30005, y30017), (x30013, y30017), (x30014, y30016), (x30014, y30023), (x30009, y30019), (x30009, y30024), (x30007, y30018), (x30014, y30020), (x30003, y30020), (x30003, y30018), (x30004, y30021), (x30010, y30022), (x30008, y30019), (x30013, y30024), (x30010, y30017), (x30003, y30019), (x30002, y30015), (x30014, y30019), (x30010, y30016), (x30010, y30023), (x30009, y30020), (x30006, y30016), (x30006, y30023), (x30002, x30011), (x30002, y30017), (x30006, y30019), (x30007, y30022), (x30010, y30024), (x30002, x30009), (x30007, y30020), (x30002, x30003), (x30005, y30024), (x30006, y30022), (x30008, y30024), (x30008, y30018), (x30005, y30016), (x30005, y30023), (x30006, y30018), (x30008, y30016), (x30008, y30023), (x30008, y30020), (x30005, y30015), (x30013, y30022), (x30012, y30020), (x30010, y30015), (x30002, y30016), (x30002, y30023), (x30011, y30020), (x30011, y30016), (x30011, y30023), (x30012, y30022), (x30011, y30017), (x30007, y30017), (x30012, y30024), (x30003, y30024), (x30011, y30024), (x30003, y30015), (x30007, y30015), (x30013, y30016), (x30013, y30023), (x30002, y30020), (x30009, y30017), (x30014, y30018), (x30008, y30022), (x30010, y30019), (x30004, y30018), (x30013, y30018), (x30002, x30012), (x30014, y30017), (x30004, y30024), (x30008, y30021), (x30009, y30018), (x30004, y30019), (x30004, y30017), (x30008, y30017), (x30013, y30020)

Conditions C:
  -

Data D:
  data_30001 = [-2.0, -2.5, -1.7, -1.9, -2.2, 1.5, 2.2, 3, 1.2, 2.8]

Continuous:  x30002, x30013, x30014
Discrete:    x30003, x30004, x30005, x30006, x30007, x30008, x30009, x30010, x30011, x30012
Conditional: 
Conditions: 

seed deactivated
==================================================
The sampler is now performing inference....
==================================================
Traceback (most recent call last):
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/unittests/models/gmm/run_gmm_1d.py", line 23, in <module>
    stats = dhmc_.sample(n_samples=n_sample,burn_in=burn_in,stepsize_range=stepsize_range,n_step_range=n_step_range,plot=False, print_stats=False, save_samples=True)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/inference/dhmc.py", line 275, in sample
    x, accept_prob, n_feval_local, n_fupdate_local = self.hmc(stepsize,n_step,x)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/inference/dhmc.py", line 240, in hmc
    x,p, n_feval_local, n_fupdate_local, _ = self.gauss_laplace_leapfrog(x,p,stepsize)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/inference/dhmc.py", line 182, in gauss_laplace_leapfrog
    x[key[0]], p[key[0]], _ = self.coordInt(x,x_embed, p, stepsize, key[0], unembed=True)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/inference/dhmc.py", line 113, in coordInt
    logp_diff = self.log_posterior(x_star, set_leafs=False, partial_unembed=unembed, key=key) - self.log_posterior(x, set_leafs=False, partial_unembed=unembed, key=key)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/utils/state.py", line 236, in _log_pdf
    _temp = self._partial_unembed(state, key)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/utils/state.py", line 287, in _partial_unembed
    unembed_var = getattr(self._unembed_state, dist_name)(state, key)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/utils/unembed.py", line 54, in unembed_Categorical
    upper = VariableCast(int_length) + lower
RuntimeError: add() received an invalid combination of arguments - got (NoneType), but expected one of:
 * (float other, float alpha)
 * (Variable other, float alpha)

Printing self._support_sizes : {'x30008': None, 'x30009': None, 'x30003': None, 'x30010': None, 'x30007': None, 'x30004': None, 'x30011': None, 'x30005': None, 'x30012': None, 'x30006': None}

Process finished with exit code 1
```
