### ISSUE TITLE
How to return two arguments in code_distributions.py

### ISSUE THREAD

**Issue by bayesianbrad** [Tobias-Kohn/PyFOPPL-2#4]
```python
 @classmethod
    def binomial(cls, args: list):
        cls.__check_arg_count('dirichlet', 2, args)
        arg = args[1]
        if isinstance(arg, SequenceType):
            return ListType(FloatType, arg.size)
        else:
            return FloatType()
```
I have had added arg = args[1] to return the size of the list of the probability of success for each trial. But, I  also need to return arg0 = arg[0] as this is the number of trials. This int value I would be put into the 'Support_size' attribute. 

Problem:
```clojure
(let [x (sample (binomial  2 [0.3, 0.5))]
  x)
```
This is a binomial with 2 trials and success prob of first trial is 0.3 and the success of the second trail is 0.5. 

Currently I am getting the following errors:
```python
(let [x (sample (binomial  2 [0.3, 0.5))]
  x)
```
```python
Traceback (most recent call last):
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/unittests/models/binomial/binomial_test.py", line 32, in <module>
    main()
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/unittests/models/binomial/binomial_test.py", line 30, in main
    base_continous_test()
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/unittests/models/binomial/binomial_test.py", line 16, in base_continous_test
    import bin as test
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/imports.py", line 28, in exec_module
    compile_module(module, input_text)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/imports.py", line 16, in compile_module
    graph, expr = compile(input_text)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/compilers.py", line 915, in compile
    ast = foppl_parser.parse(source)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/foppl_parser.py", line 359, in parse
    return parser.parse(source)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/foppl_parser.py", line 330, in parse
    return self._parsers[head].parse(form)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/foppl_parser.py", line 201, in parse
    items = [self._parse(f) for f in form.tail]
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/foppl_parser.py", line 201, in <listcomp>
    items = [self._parse(f) for f in form.tail]
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/foppl_parser.py", line 35, in _parse
    return self.parent.parse(form)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/foppl_parser.py", line 330, in parse
    return self._parsers[head].parse(form)
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/foppl_parser.py", line 275, in parse
    _, assignments = self._parse_bindings(form[1])
  File "/Users/bradley/Documents/Projects/Pyfo_project/Pyfo/pyfo/pyfoppl/foppl/foppl_parser.py", line 137, in _parse_bindings
    raise SyntaxError('let bindings must be a vector with an even number of elements')
SyntaxError: let bindings must be a vector with an even number of elements
```
I have updated all foppl_distribution.py to reflect the recently added distributions, but only in the pyfo code as I know that you don't use it and I didn't want to push any changes until this issue is resolved.

**Comment by bayesianbrad** [comment]
I realise that the support maybe extracted somewhere else, but I was unsure where.

**Comment by Tobias-Kohn** [comment]
Yes, the method you changed is for extracting the `sample_size` attribute. 
As a general hint: if you need to find the definition for `support_size`, go to where the field is defined. In this case, this is in the `graphs.py`-file. Line 345 should contain the following statement, which tells you where to change the code:
```python
self.support_size = distribution.get_support_size()
```
However, I am about making the necessary changes and will push an updated version in a few minutes.

**Comment by Tobias-Kohn** [comment]
P. S. Just to make sure: I think the _Binomial_-distribution is discrete, so the returned type should be based on integer, not on float, right? (I do realize that you just copy-pasted the definition for Dirichlet, but I'd like to make sure rather than introducing some subtle bugs)
```python
return ListType(IntegerType, arg.size)
```

**Comment by bayesianbrad** [comment]
Thanks for this Tobias, it is now clear what I should do.

Yes, you are correct, I just copied and pasted that from the Dirichlet. The
binomial will return an Int or multiple Ints in the same shape as the
output of Dirichlet

On 25 Jan 2018 11:15 pm, "Tobias Kohn" <notifications@github.com> wrote:

P. S. Just to make sure: I think the *Binomial*-distribution is discrete,
so the returned type should be based on integer, not on float, right? (I do
realize that you just copy-pasted the definition for Dirichlet)

return ListType(IntegerType, arg.size)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Tobias-Kohn/PyFOPPL-2/issues/4#issuecomment-360632679>,
or mute the thread
